### ISSUE TITLE
Is there another NuGet release planned

### ISSUE THREAD

**Issue by pchieffo** [LukasBoersma/FastCGI#4]
I'd like to get access to the latest features like Request.GetBody() but I prefer to manage my packages through NuGet.  Are you planning to push a release of the current code at some point?

**Comment by LukasBoersma** [comment]
I just published the latest version on nuget. If you notice any issues with the new body stream, please let me know.

**Comment by pchieffo** [comment]
Thank you Lukas, much appreciated!
